# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 964353fa7821ee0953fe0fd431451d8c55ddcf9948a485bcc9427bc05dd17281c939de9848dc4cce84f2542b06d41775c75e0b42158549562f4e61e5dffbf0ab

test:
  secret_key_base: 249121f4f427a0e1f5af1ddc52d3c718d86a92b926dadbf50f4ee0b2baef9403e91fcf185a2462bfc7f8b6381763212a739c70c33591d066780546fd10a44a20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
